# -*- coding: utf-8 -*-
"""dummy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tz-u1eFMwWHNt9143n102DPG0FxGd0jG
"""

print('hello')
print('its me')

"""# practice"""

print(1,2,3)